//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FaceRecog.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class diemdanh
    {
        public int IdDiemDanh { get; set; }
        public int ID { get; set; }
        public string Date { get; set; }
        public int IdMonHoc { get; set; }
        public string time { get; set; }
    
        public virtual monhoc monhoc { get; set; }
        public virtual Person Person { get; set; }
    }
}
